name: build_and_publish

on:
  pull_request:
  push:
    branches: [master]
  # Make sure we keep our free JFrog repository active :)
  schedule:
    - cron: '0 20 * * 1,4'

jobs:

  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.m2
          key: ${{ runner.os }}-scala-utils-dependencies-${{ hashFiles('**/build.sbt') }}
          # Fallback to using any cache of the dependencies if no exact match is found.
          restore-keys: ${{ runner.os }}-scala-utils-dependencies-
      - name: Setup JDK with sbt
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11
      - name: Build the project
        run: sbt compile package

  publish:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-20.04
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.m2
          key: ${{ runner.os }}-scala-utils-dependencies-${{ hashFiles('**/build.sbt') }}
          # Fallback to using any cache of the dependencies if no exact match is found.
          restore-keys: ${{ runner.os }}-scala-utils-dependencies-
      - name: Publish the project as a library
        env:
          JFROG_CREDENTIALS: ${{ secrets.JFROG_CREDENTIALS }}
        run: |
          echo "${JFROG_CREDENTIALS}" | base64 -d > credentials.properties
          sbt compile package publish
